# Generated by Django 2.1.7 on 2019-05-23 17:31

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='bought_tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Halls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=80)),
                ('vip_no', models.PositiveIntegerField(null=True)),
                ('gold_no', models.PositiveIntegerField(null=True)),
                ('platinum_no', models.PositiveIntegerField(null=True)),
                ('silver_no', models.PositiveIntegerField(null=True)),
                ('vip_price', models.FloatField(null=True)),
                ('gold_price', models.FloatField(null=True)),
                ('platinum_price', models.FloatField(null=True)),
                ('silver_price', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('released_date', models.DateField()),
                ('directed_by', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Show_times',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_time', models.TimeField()),
                ('language', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.Halls')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.Movies')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='show_times',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.Shows'),
        ),
        migrations.AddField(
            model_name='bought_tickets',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.Show_times'),
        ),
        migrations.AddField(
            model_name='bought_tickets',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.User'),
        ),
    ]
