# Generated by Django 2.1.7 on 2019-05-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show_times',
            name='gold_left',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='show_times',
            name='platinum_left',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='show_times',
            name='silver_left',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='show_times',
            name='vip_left',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
