# Generated by Django 2.1.7 on 2019-05-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_auto_20190524_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show_times',
            name='show_time',
            field=models.DateTimeField(),
        ),
    ]
