# Generated by Django 2.1.7 on 2019-05-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_auto_20190524_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='directed_by',
        ),
        migrations.AddField(
            model_name='movies',
            name='length',
            field=models.TimeField(default='02:00:00'),
        ),
    ]
