# Generated by Django 2.1.7 on 2019-05-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_auto_20190525_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show_times',
            name='language',
        ),
        migrations.AddField(
            model_name='shows',
            name='language',
            field=models.CharField(default='English', max_length=20),
        ),
    ]
