# Generated by Django 2.1.7 on 2019-05-25 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0007_auto_20190525_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show_times',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='show_times',
            name='show',
        ),
        migrations.AddField(
            model_name='movies',
            name='language',
            field=models.CharField(default='English', max_length=20),
        ),
        migrations.AddField(
            model_name='shows',
            name='show_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='shows',
            name='gold_left',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='shows',
            name='hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_app.Halls'),
        ),
        migrations.AddField(
            model_name='shows',
            name='platinum_left',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='shows',
            name='silver_left',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='shows',
            name='vip_left',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bought_tickets',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.Shows'),
        ),
        migrations.AlterField(
            model_name='shows',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_app.Movies'),
        ),
        migrations.AlterUniqueTogether(
            name='shows',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='Show_times',
        ),
        migrations.RemoveField(
            model_name='shows',
            name='language',
        ),
    ]
