# Generated by Django 2.1.7 on 2019-05-25 14:37

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('movie_app', '0008_auto_20190525_1432'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bought_tickets',
            new_name='Bought_ticket',
        ),
        migrations.RenameModel(
            old_name='Halls',
            new_name='Hall',
        ),
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
        migrations.RenameModel(
            old_name='Shows',
            new_name='Show',
        ),
    ]
