# Generated by Django 2.1.7 on 2019-05-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0009_auto_20190525_1437'),
    ]

    operations = [
        
    ]
