# Generated by Django 2.1.7 on 2019-05-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0011_show_show_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bought_ticket',
            name='paid',
            field=models.BooleanField(default='False'),
        ),
    ]
