# Generated by Django 2.1.7 on 2019-05-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0014_auto_20190528_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='bought_ticket',
            name='no_of_tickets',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
