# Generated by Django 2.1.7 on 2019-05-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0015_bought_ticket_no_of_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='bought_ticket',
            name='ticket_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
