# Generated by Django 2.1.7 on 2019-06-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0016_bought_ticket_ticket_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(null=True, upload_to='templates/movie_thumbnails'),
        ),
    ]
