# Generated by Django 2.1.7 on 2019-06-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0017_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='templates/movie_thumbnails'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(null=True, upload_to='templates/movie_posters'),
        ),
    ]
