# Generated by Django 2.1.7 on 2019-06-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0018_auto_20190603_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(null=True, upload_to='static/movie_app/movie_posters'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='static/movie_app/movie_thumbnails'),
        ),
    ]
