# Generated by Django 2.1.7 on 2019-06-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0019_auto_20190603_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(null=True, upload_to='movie_posters'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='movie_thumbnails'),
        ),
    ]
